### PR TITLE
Creating article for VMT 'vulnerability:managed' tag

### PR DESCRIPTION
**Pull request by sicarie**
Adding blog article on requirements, requesting, and links to
the process around the vulnerability:managed tag.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/openstack-security/openstack-security.github.io/14)

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 2 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfqdefAVizOCDWO1Ny:-KCfqdefAVizOCDWO1Nz:-1990306281) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L2)):_
I think markdown prefers using `#` (in various numbers) to define headers. So thi swould be

```
# The Vulnerability Management Team
```

Below would be

```
## Requirements
```

etc.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 6 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfqUJ2Tfdp6tW0_KSC:-KCfqUJ2Tfdp6tW0_KSD:-308722290) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L6)):_
`do the initial triage and *respond*`?

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 45 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfrGYB7YDhbrlLHPQn:-KCfrGYCZrXlQ7KV-ML0:955480442) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L45)):_
Might be better to say `openstack-dev` to be very clear

---

_[_posts/2016-03-22-setup-bandit-gate.markdown, line 1 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfrfkrM5lmMHW8BFdn:-KCfrfkrM5lmMHW8BFdo:2115771384) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-22-setup-bandit-gate.markdown#L1)):_
Did you mean to add this file? It seems a bit... incomplete. Also this post and the post for 03-15 probably shouldn't be in the same commit, yes?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14)_

**Comment by elmiko** [comment]
_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 7 [r2]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KD5eIm8QGaiVPglzZZB:-KD5eIm8QGaiVPglzZZC:-1002686177) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/f5a96b38e577a912fc5cec37934df41318863137/_posts/2016-03-11-vulnerability-managed-tag.markdown#L7)):_
i think the beginning of this sentence reads a little odd in context. maybe something like "This tag provides a clear indication that a project has coverage from the VMT,"

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14)_

**Comment by elmiko** [comment]
_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 15 [r2]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KD5fCtT17aKn3fcFrdq:-KD5fCtT17aKn3fcFrdr:1952940269) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/f5a96b38e577a912fc5cec37934df41318863137/_posts/2016-03-11-vulnerability-managed-tag.markdown#L15)):_
this seems overly complicated, maybe ", the VMT has a list of requirements to be fulfilled before requesting the `vulnterability:managed` tag"

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14)_

**Comment by elmiko** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14)*

**Comment by elmiko** [comment]
@sicarie lgtm, couple of suggestions take em or leave em =)

**Comment by sicarie** [comment]
Those are awesome, I will update shortly!

**Comment by sicarie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 2 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfqdefAVizOCDWO1Ny:-KCfu_JRlsv2JWrtONXc:-2131621496) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L2)):_
Ah, yeah, I had been doing RST, so that was my mistake in carrying it over. Thanks!

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 6 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfqUJ2Tfdp6tW0_KSC:-KCfuk3P636QUxPLtCJE:-309016158) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L6)):_
I ping'd Grant for review on this a few minutes ago so I'll defer to him here - does the patch and responsible disclosure count as a response?

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 45 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfrGYB7YDhbrlLHPQn:-KCfusv-mDOFO6UQ-T0q:-2035131823) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L45)):_
Good idea, I'll make the update

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 7 [r2]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KD5eIm8QGaiVPglzZZB:-KD9F1wLElPfh89dsOcA:-499146009) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/f5a96b38e577a912fc5cec37934df41318863137/_posts/2016-03-11-vulnerability-managed-tag.markdown#L7)):_
Done.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 15 [r2]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KD5fCtT17aKn3fcFrdq:-KD9F2hmiMuE54kNeJwW:-499146009) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/f5a96b38e577a912fc5cec37934df41318863137/_posts/2016-03-11-vulnerability-managed-tag.markdown#L15)):_
Done.

---

_[_posts/2016-03-22-setup-bandit-gate.markdown, line 1 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfrfkrM5lmMHW8BFdn:-KCfuvJHhAvNDvRsKfRU:-1371584979) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-22-setup-bandit-gate.markdown#L1)):_
Yeah, only meant to submit the VMT one, I'll pull these when I make the updates above.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14)_

**Comment by sicarie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 2 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfqdefAVizOCDWO1Ny:-KD9FRpTBs5JfdMFtuOd:-499146009) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L2)):_
Done.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 45 [r1]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KCfrGYB7YDhbrlLHPQn:-KD9FURBu9eRjwvODi4l:-499146009) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/36d18aee89107e369500fec3c11e3f4ed49c0303/_posts/2016-03-11-vulnerability-managed-tag.markdown#L45)):_
Done.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 7 [r2]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KD5eIm8QGaiVPglzZZB:-KD9FTW5wBSPSMQI04gn:-499146009) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/f5a96b38e577a912fc5cec37934df41318863137/_posts/2016-03-11-vulnerability-managed-tag.markdown#L7)):_
Done.

---

_[_posts/2016-03-11-vulnerability-managed-tag.markdown, line 15 [r2]](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-KD5fCtT17aKn3fcFrdq:-KD9FTwDLOarCIglB3dA:-499146009) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/f5a96b38e577a912fc5cec37934df41318863137/_posts/2016-03-11-vulnerability-managed-tag.markdown#L15)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14)_

**Comment by elmiko** [comment]
looks great!

**Comment by hyakuhei** [comment]
:lgtm: - would be nice to have an image in there somewhere.

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-:-KD9I_wS5z2whUA0kr2X:-476676406)_

**Comment by sigmavirus24** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/14#-:-KD9Jakv2hwWa0Rrrkqu:1417088721)_

**Comment by sicarie** [comment]
Yeah, I would agree, however I didn't want to just pull something off a Google Image search, and the only VMT-related pic I can find is https://security.openstack.org/_images/vmt-process.png which is more what happens _after_ it's under the tag. I'm definitely open to suggestions there!

**Comment by hyakuhei** [comment]
Any sort of contextual image is fine. It's just something to break up the
text a little.

**Pull request merged**
