### PR TITLE
OSIC Syntribos team Newon recap

### PR DESCRIPTION
**Pull request by cneill**
This post covers the main contributions of the Syntribos team during the Newton cycle, and some plans for our future direction.

---

This change is [Reviewable](https://reviewable.io/reviews/openstack-security/openstack-security.github.io/29)

### CODE REVIEW

**Comment by sigmavirus24** [comment]
First thing (I haven't even reviewed the post yet): Syntribos is an OpenStack Security Group Project. You may be part of OSIC, but the project is governed by the Security Group and the TC. If you want to call it an OSIC project, I'd strongly advise removing the project from the security group.

**Comment by sigmavirus24** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 3 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHrwKB-wjG9_9uTUjK:-KUHrwKB-wjG9_9uTUjL:b-fhogwm) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L3)):_

> ``` Markdown
> ---
> layout: post
> title:  "OSIC Syntribos team recap for Newton"
> ```

Again, "OSIC" doesn't belong here.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 13 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHsIQoNl-VGS2BZ9rZ:-KUHsIQoNl-VGS2BZ9r_:bvcuxio) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L13)):_

> ``` Markdown
> 
> - Improve [Syntribos][syntribos] to the point that it was reliable and useful
>   for testing the 6 [OSIC] key projects ([keystone], [neutron], [glance],
> ```

Is this mean to be a link reference? If you want markdown to consider these links, you need

``` mkd
[OSIC][] key projects ([keystone][], [neutron][], [glance][], [nova][], [cinder][], and [swift][])


[OSIC]: http://example.com
[keystone]: ...
[neutron]: ...
...
```

Further, is it really important that these are "OSIC key projects"? I think this will only serve to alienate other projects that would otherwise contribute to add Syntribos to their projects. You're saying "Our focus was this because of this corporate backer" not "Our focus was reliability, stability, and correctness based off of the results testing against x, y, z". The former is extraordinarily exclusionary to the rest of the community.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 19 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHswCQnDCLK-IFPViB:-KUHswCQnDCLK-IFPViC:b8me47h) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L19)):_

> ``` Markdown
>   Syntribos
> 
> We succeeded in making Syntribos more configurable, easier to use, and less
> ```

You succeeded in making it more configurable, but i t wasn't a goal? Maybe don't mention it first then. Perhaps you could simply use a bulleted list to point out the achievements of the cycle?

```
In Newton, we actually:

- Made Syntribos easier to use
- Removed false positives
- Added several new features including ...
- Removed technical debt
- Improved maintainability (adding comments and unit tests; making the project easier to contribute to)
- Increased ease of configuration
- Added test data for the 6 projects above and reported several bugs to them
```

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 29 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHtiEH4GrpciRpgZJ0:-KUHtiEH4GrpciRpgZJ1:bhcw01m) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L29)):_

> ``` Markdown
> development. This included cleaning up the codebase, creating documentation with
> sphinx, fixing bugs, writing unit tests, and adding docstrings, among other
> changes. We also removed our dependency on OpenCAFE at the request of some in
> ```

You might also point out how this will allow you to make significant performance improvements in the future.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 38 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHtnpcYATlQ47SRLJV:-KUHtnpcYATlQ47SRLJW:b-ptyvl1) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L38)):_

> ``` Markdown
> We attended the OpenStack Security Project (OSSP) midcycle at IBM's offices in
> Austin, helping out with two OpenStack Security Notes (OSSNs), participating in
> the Threat Analysis (TA) process for the barbican project, and collecting
> ```

This has now changed focus from "Here's what syntribos is and the strides it has made" to "Here's what the team has done as a whole". If this is just a puff piece about what the OSIC team has done, it doesn't belong on this blog in my opinion.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 72 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHu4TFFnB6mvO9IqBu:-KUHu4TFFnB6mvO9IqBv:bhedehn) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L72)):_

> ``` Markdown
> - Commits: **158** [[3]]
> - Code reviews: **513** [[3]]
> - Lines committed: **24,430** [[3]]
> ```

These might be interesting metrics to the OSIC governance board but I'm not sure the audience of this blog will care very much about these.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 91 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHuGf7i3oj-UADdnCA:-KUHuGf7i3oj-UADdnCB:b-kvwl3s) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L91)):_

> ``` Markdown
>     - Launchpad: https://bugs.launchpad.net/keystone/+bug/1613901
> 
> - **Potential information disclosure in "EC2 Credentials"**
> ```

If this is embargoed still, even mentioning it here is a severe violation of the VMT process. You're effectively forcing them to make this public security before they're ready.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 107 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHuprFHGfCezkVC5ZX:-KUHuprFHGfCezkVC5ZY:b1b75xp) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L107)):_

> ``` Markdown
> 
> - Removing OpenCAFE took several weeks, and while it removed a large dependency,
>   it cut down on time for other improvements
> ```

Is this for a tl;dr kind of section?

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 142 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHuZcPkS6-B_XKwtEZ:-KUHuZcPkS6-B_XKwtE_:b-abj9x5) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L142)):_

> ``` Markdown
> 
> Members of OSIC Syntribos Team
> ==============================
> ```

Again, this should just be the members of the Syntribos team, regardless of OSIC affiliation or not. Their corporate affiliation should also be next to their names and their names should be sorted alphabetically.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29)_

**Comment by mcpeak** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 13 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHsIQoNl-VGS2BZ9rZ:-KUIWg-pH2acBX8Awttb:bx9uj39) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L13)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> Is this mean to be a link reference? If you want markdown to consider these links, you need
> 
> ``` mkd
> [OSIC][] key projects ([keystone][], [neutron][], [glance][], [nova][], [cinder][], and [swift][])
> 
> 
> [OSIC]: http://example.com
> [keystone]: ...
> [neutron]: ...
> ...
> ```
> 
> Further, is it really important that these are "OSIC key projects"? I think this will only serve to alienate other projects that would otherwise contribute to add Syntribos to their projects. You're saying "Our focus was this because of this corporate backer" not "Our focus was reliability, stability, and correctness based off of the results testing against x, y, z". The former is extraordinarily exclusionary to the rest of the community.
> </details>
> I don't have a problem with it.  It explains why those were the first projects chosen.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 38 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHtnpcYATlQ47SRLJV:-KUIXZznqngWGzgJtNjc:bpm0lhu) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L38)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> This has now changed focus from "Here's what syntribos is and the strides it has made" to "Here's what the team has done as a whole". If this is just a puff piece about what the OSIC team has done, it doesn't belong on this blog in my opinion.
> </details>
> Again, I don't have a problem with the OSIC mention.  OSIC is investing a lot in OpenStack and it's reasonable that they should get credit for it.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29)_

**Comment by sigmavirus24** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 38 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHtnpcYATlQ47SRLJV:-KUI_xECUIjQcimplCcq:bngp69w) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L38)):_
<details><summary>

<i>Previously, mcpeak (Travis McPeak) wrote…</i></summary>



> Again, I don't have a problem with the OSIC mention.  OSIC is investing a lot in OpenStack and it's reasonable that they should get credit for it.
> </details>
> I've spoken to OSIC leadership and they agree that this blog post belongs on the OSIC blog (as it is currently written). I'm not adverse to giving OSIC credit for giving Charles, etc. time to work on Syntribos, but if you read every other post on this blog and then read this one, there's a large disconnect in the topic. This reads as a "End of Cycle Team Update" rather than every other post which is focused on the OSSP and it's projects. This _does_ touch on Syntribos, but it is jarringly different from the rest. Maybe that's fine, but in my opinion, it fails to fit nicely in with the rest of the content.

Also, OSIC is backed by two large companies who do enough to promote their own contributions to OpenStack. We can acknowledge that without this blog post dripping with OSIC references.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29)_

**Comment by cneill** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 13 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHsIQoNl-VGS2BZ9rZ:-KUJQPeOm2XkujiGcdPI:b-93dr53) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L13)):_
<details><summary>

<i>Previously, mcpeak (Travis McPeak) wrote…</i></summary>



> I don't have a problem with it.  It explains why those were the first projects chosen.
> </details>
> It appears that Github will actually render it without the empty brackets, but I've added them just to be safe.

As for calling out the OSIC key projects, I'm not speaking for why OSIC chose those projects, or giving any kind of opinion as to the relative importance of other projects - I'm simply stating that OSIC has picked some projects that it cares about, and we tested those. Anything else is dishonest. Implying that we _chose_ to test those projects because X, Y, and Z is not true. I've modified the language some so that hopefully it's clearer.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 19 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHswCQnDCLK-IFPViB:-KUJRzqrh1HFaY8tskog:bwmm6a2) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L19)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> You succeeded in making it more configurable, but i t wasn't a goal? Maybe don't mention it first then. Perhaps you could simply use a bulleted list to point out the achievements of the cycle?
> 
> ```
> In Newton, we actually:
> 
> - Made Syntribos easier to use
> - Removed false positives
> - Added several new features including ...
> - Removed technical debt
> - Improved maintainability (adding comments and unit tests; making the project easier to contribute to)
> - Increased ease of configuration
> - Added test data for the 6 projects above and reported several bugs to them
> ```
> 
> </details>
> Configurability would fit under the umbrella of making Syntribos "reliable and useful" in the first list of goals

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 38 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHtnpcYATlQ47SRLJV:-KUJSdwQU54UDMz-GWR8:bo7mewc) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L38)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> I've spoken to OSIC leadership and they agree that this blog post belongs on the OSIC blog (as it is currently written). I'm not adverse to giving OSIC credit for giving Charles, etc. time to work on Syntribos, but if you read every other post on this blog and then read this one, there's a large disconnect in the topic. This reads as a "End of Cycle Team Update" rather than every other post which is focused on the OSSP and it's projects. This _does_ touch on Syntribos, but it is jarringly different from the rest. Maybe that's fine, but in my opinion, it fails to fit nicely in with the rest of the content.
> 
> Also, OSIC is backed by two large companies who do enough to promote their own contributions to OpenStack. We can acknowledge that without this blog post dripping with OSIC references.
> </details>
> Full disclosure: I wrote a retrospective for OSIC leadership and copied it, with a number of modifications, for this blog post. I've removed this paragraph, since I agree that most people reading the blog probably don't care about the team as much as the project.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 72 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHu4TFFnB6mvO9IqBu:-KUJT-rZYaS6xMEusD_a:betiuuc) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L72)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> These might be interesting metrics to the OSIC governance board but I'm not sure the audience of this blog will care very much about these.
> </details>
> I removed these top 3 since they're just kind of vanity metrics and don't speak much to improvements in the codebase

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29)_

**Comment by cneill** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_[_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown, line 3 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHrwKB-wjG9_9uTUjK:-KUOUxiYPyGmZKShi0v8:b-896fix) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown#L3)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> Again, "OSIC" doesn't belong here.
> </details>
> Done.

---

_[_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown, line 29 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHtiEH4GrpciRpgZJ0:-KUOV-0p67KwRoqSOfnS:b-896fix) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown#L29)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> You might also point out how this will allow you to make significant performance improvements in the future.
> </details>
> Done.

---

_[_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown, line 91 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHuGf7i3oj-UADdnCA:-KUOV1uvonP-3Dy9NaSt:b-896fix) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown#L91)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> If this is embargoed still, even mentioning it here is a severe violation of the VMT process. You're effectively forcing them to make this public security before they're ready.
> </details>
> Done.

---

_[_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown, line 142 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHuZcPkS6-B_XKwtEZ:-KUOV449yaEcnLywMQ8G:b-896fix) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-17-osic-syntribos-team-recap-for-newton.markdown#L142)):_
<details><summary>

<i>Previously, sigmavirus24 (Ian Cordasco) wrote…</i></summary>



> Again, this should just be the members of the Syntribos team, regardless of OSIC affiliation or not. Their corporate affiliation should also be next to their names and their names should be sorted alphabetically.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29)_

**Comment by mcpeak** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-:-KUPTByj_W_Fptlun0nR:bb6ywmx)_

**Comment by sigmavirus24** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

_[_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown, line 13 at r1](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-KUHsIQoNl-VGS2BZ9rZ:-KUIasaQSlqVIZn7yQFx:bb6s6rz) ([raw file](https://github.com/openstack-security/openstack-security.github.io/blob/31ae15e4223f4af6452134411c2f89d0c4d616d5/_posts/2016-10-14-osic-syntribos-team-recap-for-newton.markdown#L13)):_
<details><summary>

<i>Previously, mcpeak (Travis McPeak) wrote…</i></summary>



> I don't have a problem with it.  It explains why those were the first projects chosen.
> </details>
> @tmc

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openstack-security/openstack-security.github.io/29#-:-KURqojCy-mYkGQjTOqT:bnfp4nl)_

**Comment by cneill** [comment]
Any other concerns before we merge this?

**Comment by mcpeak** [comment]
Ship it!

**Pull request merged**
